### PR TITLE
Added code for model and service for FabricVpcDomainPolicy

### PR DESCRIPTION
**Pull request by FrederikSuijs**
Hello, 
I'm trying contribute to the aci_ Terraform modules and have created the necessary model and service objects in this repository required to implement [https://github.com/CiscoDevNet/terraform-provider-aci/issues/198](https://github.com/CiscoDevNet/terraform-provider-aci/issues/198)
This is my first attempt to add to a public repo. Most of the code is created by using the well known "copy/paste/replace" method. I have tried to test as much as I can. Small mistakes or convention inconsistencies are always possible, please bear this in mind.

Once this is merged in the master, I will launch a new merge request into the [https://github.com/CiscoDevNet/terraform-provider-aci/](https://github.com/CiscoDevNet/terraform-provider-aci/) repo to incorporate the Terraform objects.

### CODE REVIEW

**Comment by shrsr** [comment]
@FrederikSuijs 
I have made few changes to your files which will work in tandem with our existing files in the collection. Can I push those changes to your PR?

**Comment by FrederikSuijs** [comment]
Hi @shrsr , feel free to merge the changes! Honestly I was not expecting any follow up since I raised this already 2 months ago.
Looking forward to it!

**Comment by FrederikSuijs** [comment]
Went over your changes. Seems I was on the correct path, just missing some conventions and structure. Glad you updated that. I see you mention it is being generated by script? Could you elaborate on that?
What would be next step to get this pushed to ciscoecosystem:master?

**Comment by shrsr** [comment]
Yes, there were minor changes to be made in order to make them work with newer files. The script is a basic template we want to use from now to format the new files we create. We'll review the code again and merge it with ciscoecosystem. 

Do you have the resource and datasource files? I'll review those once you make a PR on terraform-aci-provider.

**Comment by FrederikSuijs** [comment]
I did also give a shot at creating the resource and datasource files. However those are based on the previous version of the code required in this repo.
Does it make sense to lauch a PR with the outdated code?

**Comment by shrsr** [comment]
Yes. Please go ahead and make a PR with the code you have. I'll review and make changes so that it works with the newer code we have here.

**Review by lhercot — APPROVED** [review]

**Pull request merged**
